/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewsTier;

import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author anhtuan
 */
public class Product extends java.awt.Frame {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        initTableTemplate();
    }
    private void initTableTemplate(){
        jprd_control = new ControllersTier.Product_Controller();
        jtblTemplate = new javax.swing.JTable();
        jtblTemplate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Name", "Stuff", "Quantity" , "Cost", "Price", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jPanelFooter = new javax.swing.JPanel();
        jPanelMain = new javax.swing.JPanel();
        jPanelToolBar = new javax.swing.JPanel();
        jbtnNew = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnView = new javax.swing.JButton();
        jbtnBack = new javax.swing.JButton();
        jPanelParent = new javax.swing.JPanel();
        jPanelNew = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextNewId = new javax.swing.JTextField();
        jTextNewName = new javax.swing.JTextField();
        jcmbBoxNewStuff = new javax.swing.JComboBox<>();
        jSpinNewQuantity = new javax.swing.JSpinner();
        jcmbBoxNewCost = new javax.swing.JComboBox<>();
        jTextNewPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNewDes = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jlblNewName = new javax.swing.JLabel();
        jlblNewPrice = new javax.swing.JLabel();
        jbtnNewCancel = new javax.swing.JButton();
        jbtnNewSave = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtblNewProduct = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelEdit = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextEditSearch = new javax.swing.JTextField();
        jcmbBoxEditSearch = new javax.swing.JComboBox<>();
        jbtnEditSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblEditProduct = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnEditCancel = new javax.swing.JButton();
        jbtnEditRemove = new javax.swing.JButton();
        jbtnEditSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextEditId = new javax.swing.JTextField();
        jTextEditName = new javax.swing.JTextField();
        jSpinEditQuantity = new javax.swing.JSpinner();
        jcmbBoxEditCost = new javax.swing.JComboBox<>();
        jTextEditPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcmbBoxEditStuff = new javax.swing.JComboBox<>();
        jlblEditWrong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaEditDes = new javax.swing.JTextArea();
        jPanelView = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblViewProducts = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jbtnViewall = new javax.swing.JButton();
        jcmbBoxViewall = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcmbBoxViewFindout = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jTextViewSearch = new javax.swing.JTextField();
        jbtnViewSearch = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jcmbBoxViewStuff = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblViewDetails = new javax.swing.JTable();

        setTitle("Product Manage");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelHeader.setBackground(new java.awt.Color(120, 189, 217));
        add(jPanelHeader, java.awt.BorderLayout.NORTH);

        jPanelFooter.setBackground(new java.awt.Color(120, 189, 217));
        add(jPanelFooter, java.awt.BorderLayout.SOUTH);

        jPanelMain.setBackground(new java.awt.Color(255, 179, 179));

        jbtnNew.setText("New");
        jbtnNew.setActionCommand("jButton1");
        jbtnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnNewMouseClicked(evt);
            }
        });

        jbtnEdit.setText("Edit");
        jbtnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEditMouseClicked(evt);
            }
        });

        jbtnView.setText("View");
        jbtnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnViewMouseClicked(evt);
            }
        });

        jbtnBack.setText("Back");

        javax.swing.GroupLayout jPanelToolBarLayout = new javax.swing.GroupLayout(jPanelToolBar);
        jPanelToolBar.setLayout(jPanelToolBarLayout);
        jPanelToolBarLayout.setHorizontalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createSequentialGroup()
                .addComponent(jbtnNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnBack))
        );
        jPanelToolBarLayout.setVerticalGroup(
            jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbtnNew)
                .addComponent(jbtnEdit)
                .addComponent(jbtnView)
                .addComponent(jbtnBack))
        );

        jPanelParent.setLayout(new java.awt.CardLayout());

        jPanelNew.setBackground(new java.awt.Color(120, 189, 217));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));

        jLabel17.setText("Manager Id");

        jLabel18.setText("Manager Name");

        jTextField1.setText("manager id");

        jTextField2.setText("manager name");

        jLabel26.setText("MANAGER INFORMATION ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel10MouseMoved(evt);
            }
        });

        jLabel1.setText("Product ID");

        jLabel2.setText("Product Name");

        jLabel19.setText("Stuff");

        jLabel20.setText("Quantity");

        jLabel21.setText("Cost");

        jLabel22.setText("Price");

        jLabel23.setText("Description");

        jTextNewId.setText("product id");
        jTextNewId.setToolTipText("This is product id");
        jTextNewId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNewId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNewIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNewIdFocusLost(evt);
            }
        });
        jTextNewId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNewIdMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextNewIdMouseExited(evt);
            }
        });
        jTextNewId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNewIdActionPerformed(evt);
            }
        });
        jTextNewId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNewIdKeyPressed(evt);
            }
        });

        jTextNewName.setText("product name");
        jTextNewName.setToolTipText("Click here to set product name");
        jTextNewName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNewNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNewNameFocusLost(evt);
            }
        });
        jTextNewName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNewNameMouseClicked(evt);
            }
        });

        jcmbBoxNewStuff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirt", "Shorts", "Shoes", "Skins-care" }));
        jcmbBoxNewStuff.setToolTipText("Stuff of products");

        jSpinNewQuantity.setToolTipText("Numbers of product");

        jcmbBoxNewCost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "25%", "30%", "50%", "75%" }));
        jcmbBoxNewCost.setToolTipText("Discount for product");

        jTextNewPrice.setText("product price");
        jTextNewPrice.setToolTipText("Click here to set price of this product");
        jTextNewPrice.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextNewPriceComponentAdded(evt);
            }
        });
        jTextNewPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextNewPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextNewPriceFocusLost(evt);
            }
        });
        jTextNewPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNewPriceMouseClicked(evt);
            }
        });
        jTextNewPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNewPriceKeyReleased(evt);
            }
        });

        jTextAreaNewDes.setColumns(20);
        jTextAreaNewDes.setRows(5);
        jTextAreaNewDes.setText("product description");
        jTextAreaNewDes.setToolTipText("Click here to set the product's description");
        jTextAreaNewDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaNewDesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaNewDesFocusLost(evt);
            }
        });
        jTextAreaNewDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaNewDesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaNewDes);

        jLabel25.setText("SET NEW PRODUCT HERE");

        jbtnNewCancel.setText("Cancel");

        jbtnNewSave.setText("Save");
        jbtnNewSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnNewSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jbtnNewCancel))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextNewId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcmbBoxNewStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcmbBoxNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtnNewSave, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNewId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcmbBoxNewStuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))
                            .addComponent(jlblNewName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jSpinNewQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jcmbBoxNewCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(jTextNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnNewSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnNewCancel)))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setPreferredSize(new java.awt.Dimension(400, 216));

        jLabel24.setText("TABLE OF CURRENT NEW PRODUCT");

        jtblNewProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "STUFF", "QUANTITY", "COST", "PRICE", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblNewProduct.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jtblNewProduct);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(0, 153, 153));
        jPanel14.setPreferredSize(new java.awt.Dimension(304, 216));

        jLabel29.setText("TABLE OF BACKUP PRODUCT");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "STUFF", "QUANTITY", "COST", "PRICE", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable2);

        jButton1.setText("BACKUP");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(0, 153, 153));
        jPanel15.setPreferredSize(new java.awt.Dimension(283, 216));

        jLabel28.setText("TABLE OF EDIT PRODUCT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "STUFF", "QUANTITY", "COST", "PRICE", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelNewLayout = new javax.swing.GroupLayout(jPanelNew);
        jPanelNew.setLayout(jPanelNewLayout);
        jPanelNewLayout.setHorizontalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNewLayout.createSequentialGroup()
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
        );
        jPanelNewLayout.setVerticalGroup(
            jPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelNewLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelNew, "card2");

        jPanelEdit.setBackground(new java.awt.Color(120, 189, 217));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTextEditSearch.setText("Click here to entry");
        jTextEditSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEditSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEditSearchFocusLost(evt);
            }
        });

        jcmbBoxEditSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Name", "Stuff", "Quantity", "Cost", "Price", "Description" }));

        jbtnEditSearch.setText("Search");
        jbtnEditSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEditSearchMouseClicked(evt);
            }
        });

        jtblEditProduct.setAutoCreateRowSorter(true);
        jtblEditProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Stuff", "Quantity", "Cost", "Price", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblEditProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEditProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblEditProduct);

        jLabel27.setText("Choose Key To Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextEditSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbBoxEditSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbBoxEditSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEditSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jbtnEditCancel.setText("Cancel");

        jbtnEditRemove.setText("Remove");
        jbtnEditRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEditRemoveMouseClicked(evt);
            }
        });

        jbtnEditSave.setText("Save");
        jbtnEditSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEditSaveMouseClicked(evt);
            }
        });

        jLabel3.setText("Id");

        jLabel4.setText("Name");

        jLabel5.setText("Quantity");

        jLabel6.setText("Price");

        jLabel7.setText("Cost");

        jTextEditId.setText("product id");
        jTextEditId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEditIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEditIdFocusLost(evt);
            }
        });

        jTextEditName.setText("product name");
        jTextEditName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEditNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEditNameFocusLost(evt);
            }
        });

        jcmbBoxEditCost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "10%", "25%", "30%", "50%", "75%" }));

        jTextEditPrice.setText("product price");
        jTextEditPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextEditPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextEditPriceFocusLost(evt);
            }
        });

        jLabel9.setText("Stuff");

        jcmbBoxEditStuff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shirt", "Shorts", "Shoes", "Skins-care" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextEditName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEditId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmbBoxEditStuff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmbBoxEditCost, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jlblEditWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextEditId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextEditName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinEditQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbBoxEditStuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmbBoxEditCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblEditWrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setText("Description");

        jTextAreaEditDes.setColumns(20);
        jTextAreaEditDes.setRows(5);
        jTextAreaEditDes.setText("product description");
        jTextAreaEditDes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaEditDesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaEditDesFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jTextAreaEditDes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtnEditCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnEditRemove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnEditSave)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEditCancel)
                    .addComponent(jbtnEditRemove)
                    .addComponent(jbtnEditSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelEditLayout = new javax.swing.GroupLayout(jPanelEdit);
        jPanelEdit.setLayout(jPanelEditLayout);
        jPanelEditLayout.setHorizontalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelEditLayout.setVerticalGroup(
            jPanelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelParent.add(jPanelEdit, "card3");

        jPanelView.setBackground(new java.awt.Color(120, 189, 217));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel12.setText("Products");

        jtblViewProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblViewProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblViewProductsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtblViewProducts);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel10.setText("Over View");

        jbtnViewall.setBackground(new java.awt.Color(255, 204, 204));
        jbtnViewall.setText("View All");
        jbtnViewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnViewallMouseClicked(evt);
            }
        });

        jcmbBoxViewall.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Shirts", "Shorts", "Shoes", "Skins Care" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jcmbBoxViewall, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jbtnViewall)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnViewall)
                    .addComponent(jcmbBoxViewall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel11.setText("Find Oject");

        jLabel14.setText("Object to Find");

        jcmbBoxViewFindout.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Id", "Name", "Quantity", "Cost", "Price" }));

        jLabel15.setText("Find here");

        jTextViewSearch.setText("Enter object name to find");
        jTextViewSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextViewSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextViewSearchFocusLost(evt);
            }
        });

        jbtnViewSearch.setBackground(new java.awt.Color(255, 204, 204));
        jbtnViewSearch.setText("Search");

        jLabel16.setText("for");

        jcmbBoxViewStuff.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Shirts", "Shorts", "Shoes", "Skins Care" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbBoxViewFindout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmbBoxViewStuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextViewSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnViewSearch)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcmbBoxViewFindout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jcmbBoxViewStuff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextViewSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnViewSearch))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setText("More Product Details");

        jtblViewDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Stuff", "Quantity", "Cost", "Price", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtblViewDetails);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5))
        );

        javax.swing.GroupLayout jPanelViewLayout = new javax.swing.GroupLayout(jPanelView);
        jPanelView.setLayout(jPanelViewLayout);
        jPanelViewLayout.setHorizontalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewLayout.createSequentialGroup()
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelViewLayout.setVerticalGroup(
            jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelViewLayout.createSequentialGroup()
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelParent.add(jPanelView, "card4");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jPanelToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jbtnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditMouseClicked
        showPanelEdit();
    }//GEN-LAST:event_jbtnEditMouseClicked

    private void jbtnNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnNewMouseClicked

        showPanelNew();
    }//GEN-LAST:event_jbtnNewMouseClicked

    private void jbtnViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnViewMouseClicked

        showPanelView();
    }//GEN-LAST:event_jbtnViewMouseClicked

    private void jTextNewIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNewIdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewIdMouseClicked

    private void jTextNewNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNewNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewNameMouseClicked

    private void jTextNewPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNewPriceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewPriceMouseClicked

    private void jTextAreaNewDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaNewDesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaNewDesMouseClicked

    private void jTextNewIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNewIdMouseExited

    }//GEN-LAST:event_jTextNewIdMouseExited

    private void jTextNewIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNewIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewIdKeyPressed

    private void jPanel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseMoved

    private void jTextNewIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNewIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewIdActionPerformed

    private void jTextNewIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewIdFocusGained
        // TODO add your handling code here:
        handleNewId();
    }//GEN-LAST:event_jTextNewIdFocusGained

    private void jTextNewIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewIdFocusLost
        // TODO add your handling code here:
        handleNewId();
    }//GEN-LAST:event_jTextNewIdFocusLost

    private void jTextNewNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewNameFocusGained
        // TODO add your handling code here:
        handleNewName();
    }//GEN-LAST:event_jTextNewNameFocusGained

    private void jTextNewNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewNameFocusLost
        // TODO add your handling code here:
        handleNewName();
    }//GEN-LAST:event_jTextNewNameFocusLost

    private void jTextNewPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewPriceFocusGained
        // TODO add your handling code here:
        handleNewPrice();
        handleNewPriceAdd();
    }//GEN-LAST:event_jTextNewPriceFocusGained

    private void jTextNewPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextNewPriceFocusLost
        // TODO add your handling code here:
        handleNewPrice();
    }//GEN-LAST:event_jTextNewPriceFocusLost

    private void jTextAreaNewDesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaNewDesFocusGained
        // TODO add your handling code here:
        handleNewDes();
    }//GEN-LAST:event_jTextAreaNewDesFocusGained

    private void jTextAreaNewDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaNewDesFocusLost
        // TODO add your handling code here:
        handleNewDes();
    }//GEN-LAST:event_jTextAreaNewDesFocusLost

    private void jbtnNewSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnNewSaveMouseClicked
        // TODO add your handling code here:
        handleNewSave();
    }//GEN-LAST:event_jbtnNewSaveMouseClicked

    private void jTextEditSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditSearchFocusGained
        // TODO add your handling code here:
        handleEditSearch();
    }//GEN-LAST:event_jTextEditSearchFocusGained

    private void jTextEditSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditSearchFocusLost
        // TODO add your handling code here:
        handleEditSearch();
    }//GEN-LAST:event_jTextEditSearchFocusLost

    private void jTextEditIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditIdFocusGained
        // TODO add your handling code here:
        handleEditId();
    }//GEN-LAST:event_jTextEditIdFocusGained

    private void jTextEditIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditIdFocusLost
        // TODO add your handling code here:
        handleEditId();
    }//GEN-LAST:event_jTextEditIdFocusLost

    private void jTextEditNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditNameFocusGained
        // TODO add your handling code here:
        handleEditName();
    }//GEN-LAST:event_jTextEditNameFocusGained

    private void jTextEditNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditNameFocusLost
        // TODO add your handling code here:
        handleEditName();
    }//GEN-LAST:event_jTextEditNameFocusLost

    private void jTextEditPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditPriceFocusGained
        // TODO add your handling code here:
        handleEditPrice();
    }//GEN-LAST:event_jTextEditPriceFocusGained

    private void jTextEditPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextEditPriceFocusLost
        // TODO add your handling code here:
        handleEditPrice();
    }//GEN-LAST:event_jTextEditPriceFocusLost

    private void jTextAreaEditDesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaEditDesFocusGained
        // TODO add your handling code here:
        handleEditDes();
    }//GEN-LAST:event_jTextAreaEditDesFocusGained

    private void jTextAreaEditDesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaEditDesFocusLost
        // TODO add your handling code here:
        handleEditDes();
    }//GEN-LAST:event_jTextAreaEditDesFocusLost

    private void jTextViewSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextViewSearchFocusGained
        // TODO add your handling code here:
        handleViewSearch();
    }//GEN-LAST:event_jTextViewSearchFocusGained

    private void jTextViewSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextViewSearchFocusLost
        // TODO add your handling code here:
        handleViewSearch();
    }//GEN-LAST:event_jTextViewSearchFocusLost

    private void jbtnEditSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditSearchMouseClicked
        // TODO add your handling code here:
        handleEditTable();
    }//GEN-LAST:event_jbtnEditSearchMouseClicked

    private void jtblEditProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEditProductMouseClicked
        // TODO add your handling code here:
        handleEditModifier();
    }//GEN-LAST:event_jtblEditProductMouseClicked

    private void jbtnEditSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditSaveMouseClicked
        // TODO add your handling code here:
        handleEditSave();
    }//GEN-LAST:event_jbtnEditSaveMouseClicked

    private void jbtnEditRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditRemoveMouseClicked
        // TODO add your handling code here:
        handleEditRemove();
    }//GEN-LAST:event_jbtnEditRemoveMouseClicked

    private void jTextNewPriceComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextNewPriceComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNewPriceComponentAdded

    private void jTextNewPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNewPriceKeyReleased
        // TODO add your handling code here:
        handleNewPriceAdd();
    }//GEN-LAST:event_jTextNewPriceKeyReleased

    private void jbtnViewallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnViewallMouseClicked
        // TODO add your handling code here:
        handleViewOverview();
    }//GEN-LAST:event_jbtnViewallMouseClicked

    private void jtblViewProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblViewProductsMouseClicked
        // TODO add your handling code here:
        handleViewViewDetail();
    }//GEN-LAST:event_jtblViewProductsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }
    private javax.swing.JTable jtblTemplate;
    private ControllersTier.Product_Controller jprd_control;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelNew;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelToolBar;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSpinner jSpinEditQuantity;
    private javax.swing.JSpinner jSpinNewQuantity;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaEditDes;
    private javax.swing.JTextArea jTextAreaNewDes;
    private javax.swing.JTextField jTextEditId;
    private javax.swing.JTextField jTextEditName;
    private javax.swing.JTextField jTextEditPrice;
    private javax.swing.JTextField jTextEditSearch;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextNewId;
    private javax.swing.JTextField jTextNewName;
    private javax.swing.JTextField jTextNewPrice;
    private javax.swing.JTextField jTextViewSearch;
    private javax.swing.JButton jbtnBack;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnEditCancel;
    private javax.swing.JButton jbtnEditRemove;
    private javax.swing.JButton jbtnEditSave;
    private javax.swing.JButton jbtnEditSearch;
    private javax.swing.JButton jbtnNew;
    private javax.swing.JButton jbtnNewCancel;
    private javax.swing.JButton jbtnNewSave;
    private javax.swing.JButton jbtnView;
    private javax.swing.JButton jbtnViewSearch;
    private javax.swing.JButton jbtnViewall;
    private javax.swing.JComboBox<String> jcmbBoxEditCost;
    private javax.swing.JComboBox<String> jcmbBoxEditSearch;
    private javax.swing.JComboBox<String> jcmbBoxEditStuff;
    private javax.swing.JComboBox<String> jcmbBoxNewCost;
    private javax.swing.JComboBox<String> jcmbBoxNewStuff;
    private javax.swing.JComboBox<String> jcmbBoxViewFindout;
    private javax.swing.JComboBox<String> jcmbBoxViewStuff;
    private javax.swing.JComboBox<String> jcmbBoxViewall;
    private javax.swing.JLabel jlblEditWrong;
    private javax.swing.JLabel jlblNewName;
    private javax.swing.JLabel jlblNewPrice;
    private javax.swing.JTable jtblEditProduct;
    private javax.swing.JTable jtblNewProduct;
    private javax.swing.JTable jtblViewDetails;
    private javax.swing.JTable jtblViewProducts;
    // End of variables declaration//GEN-END:variables

    private void showPanelEdit(){
        CardLayout cl = (CardLayout) this.jPanelParent.getLayout();
        cl.show(jPanelParent, "card3");
    }
    private void showPanelNew(){
        CardLayout cl = (CardLayout) this.jPanelParent.getLayout();
        cl.show(jPanelParent, "card2");
    }
    private void showPanelView(){
        CardLayout cl = (CardLayout) this.jPanelParent.getLayout();
        cl.show(jPanelParent, "card4");
    }
    private void handleNewId(){
        String temp = this.jTextNewId.getText();
        if(temp.equals("product id"))this.jTextNewId.setText("");
        else if(temp.equals(""))this.jTextNewId.setText("product id");
    }
    private void handleNewName(){
        String temp = this.jTextNewName.getText();
        if(temp.equals("product name"))this.jTextNewName.setText("");
        else if(temp.equals(""))this.jTextNewName.setText("product name");
    }
    private void handleNewPrice(){
        String temp = this.jTextNewPrice.getText();
        if(temp.equals("product price"))this.jTextNewPrice.setText("");
        else if(temp.equals(""))this.jTextNewPrice.setText("product price");
    }
    private void handleNewDes(){
        String temp = this.jTextAreaNewDes.getText();
        if(temp.equals("product description"))this.jTextAreaNewDes.setText("");
        else if(temp.equals(""))this.jTextAreaNewDes.setText("product description");
    }
    private void handleNewSave(){
        String id = this.jTextNewId.getText();
        String name = this.jTextNewName.getText();
        String stuff = this.jcmbBoxNewStuff.getSelectedItem().toString();
        String quantity = this.jSpinNewQuantity.getValue().toString();
        String cost = this.jcmbBoxNewCost.getSelectedItem().toString();
        String price = this.jTextNewPrice.getText();
        String des = this.jTextAreaNewDes.getText();
        boolean ctrl_price = this.jprd_control.checkProductPrice(price);
        boolean flag = true;
        if(name.equals("product name")){this.jlblNewName.setText("<html>please entrie <br/>name to product</html>"); flag = false;}
        else this.jlblNewName.setText("");
        if(ctrl_price == false){this.jlblNewPrice.setText("<html>Price to product includes number (0,1,2,3,...)</html>"); flag = false;}
        else{
            this.jlblNewPrice.setText("");
            this.jTextNewPrice.setText(this.jprd_control.modifierProductPrice(price));
        }
        if(flag == true){
            Object [] rows = {id, name, stuff, quantity, cost, price, des};
            DefaultTableModel model = (DefaultTableModel) this.jtblNewProduct.getModel();
            model.addRow(rows);
            this.jTextNewId.setText("product id");
            this.jTextNewName.setText("product name");
            this.jcmbBoxNewStuff.setSelectedIndex(0);
            this.jSpinNewQuantity.setValue(0);
            this.jcmbBoxNewCost.setSelectedIndex(0);
            this.jTextNewPrice.setText("product price");
            this.jTextAreaNewDes.setText("product description");
            DefaultTableModel tempmod = (DefaultTableModel) this.jtblTemplate.getModel();
            tempmod.addRow(rows);
        }
    }
    private void handleEditSearch(){
        String temp = this.jTextEditSearch.getText();
        if(temp.equals("Click here to entry"))this.jTextEditSearch.setText("");
        else if(temp.equals(""))this.jTextEditSearch.setText("Click here to entry");
    }
    private void handleEditId(){
        String temp = this.jTextEditId.getText();
        if(temp.equals("product id"))this.jTextEditId.setText("");
        else if(temp.equals(""))this.jTextEditId.setText("product id");
    }
    private void handleEditName(){
        String temp = this.jTextEditName.getText();
        if(temp.equals("product name"))this.jTextEditName.setText("");
        else if(temp.equals(""))this.jTextEditName.setText("product name");
    }
    private void handleEditPrice(){
        String temp = this.jTextEditPrice.getText();
        if(temp.equals("product price"))this.jTextEditPrice.setText("");
        else if(temp.equals(""))this.jTextEditPrice.setText("product price");
    }
    private void handleEditDes(){
        String temp = this.jTextAreaEditDes.getText();
        if(temp.equals("product description"))this.jTextAreaEditDes.setText("");
        else if(temp.equals(""))this.jTextAreaEditDes.setText("product description");
    }
    private void handleViewSearch(){
        String temp = this.jTextViewSearch.getText();
        if(temp.equals("Enter object name to find"))this.jTextViewSearch.setText("");
        else if(temp.equals(""))this.jTextViewSearch.setText("Enter object name to find");
    }
    private void handleEditTable(){
        ClearEditProductTable();
        int index_S = this.jcmbBoxEditSearch.getSelectedIndex();
        String str_S = this.jTextEditSearch.getText();
        int rows = this.jtblTemplate.getRowCount();
        int cols = this.jtblTemplate.getColumnCount();
        if(index_S != 6){
            for(int i = 0; i < rows; i++){
                Object [] o = new Object [] {null, null, null, null, null, null, null};
                if(str_S.equals(this.jtblTemplate.getValueAt(i, index_S).toString()))
                    for(int j = 0; j < cols; j++){
                        o[j] = this.jtblTemplate.getValueAt(i, j);
                    }
                if(o[0] != null){
                    DefaultTableModel model = (DefaultTableModel)this.jtblEditProduct.getModel();
                    model.addRow(o);
                }
            }
        }
        else{
            EditSearchTable(index_S, str_S, rows);
        }
    }
    private void ClearEditProductTable(){
        DefaultTableModel model = (DefaultTableModel)this.jtblEditProduct.getModel();
        for(int i = model.getRowCount() - 1; i >= 0; i--){
            model.removeRow(i);
        }
    }
    private void EditSearchTable(int index_S, String str_S, int rows){
        boolean flag = false;
        boolean flag_read = false;
        Object [] split_search = str_S.split(" ");
        int [] arr_read = new int [100];
        int [][] count = new int[100][2];
        for(int i = 0; i < 100; i++)count[i][1] = 0;
        for(int i = 0; i < 100; i++)arr_read[i] = -1;
        int len1 = split_search.length;
        int temp = 0;
        for(int i = 0; i < rows; i++){
            int temp_read = 0;
            Object [] split_fromTable = this.jtblTemplate.getValueAt(i,index_S).toString().split(" ");
            int len2 = split_fromTable.length;
            for(int j = 0; j < len1; j++){
                for(int k = 0; k < len2; k++){
                    if(split_fromTable[k].toString().equals(split_search[j].toString())){
                        for(int c = 0; c < arr_read.length; c++)if(k == arr_read[c])flag_read = true;
                        if(flag_read != true){
                            if(flag == false)
                                count[temp][0] = Integer.parseInt(this.jtblTemplate.getValueAt(i,0).toString());
                            count[temp][1]++;
                            flag = true;
                            arr_read[temp_read] = k;
                        }
                    }
                }
            }
            if(flag == true){
                flag = false;
                flag_read = false;
                temp++;
            }
        }
        int min = count[0][1];
        for(int i = 0; i < temp; i++)
            for(int j = 0; j < temp - i; j++)
                if(min < count[j][1]){
                    min = count[j][1];
                    int tempid = count[j][0];
                    int tempval = count[j][1];
                    count[j][0] = count[i][0];
                    count[j][1] = count[i][1];
                    count[i][0] = tempid;
                    count[i][1] = tempval;
                }
        for(int i = 0; i < temp; i++)
            for(int j = 0; j < rows; j++)
                    if(this.jtblTemplate.getValueAt(j, 0).toString().equals(String.valueOf(count[i][0]))){
                        DefaultTableModel model = (DefaultTableModel)this.jtblEditProduct.getModel();
                        Object [] r_add = new Object [] {this.jtblTemplate.getValueAt(j,0).toString(),this.jtblTemplate.getValueAt(j, 1).toString()
                        , this.jtblTemplate.getValueAt(j, 2).toString(), this.jtblTemplate.getValueAt(j, 3).toString(), this.jtblTemplate.getValueAt(j, 4).toString(),
                        this.jtblTemplate.getValueAt(j, 5).toString(), this.jtblTemplate.getValueAt(j, 6).toString()};
                        model.addRow(r_add);
                    }
    }
    private void handleEditModifier(){
        int index = this.jtblEditProduct.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)this.jtblEditProduct.getModel();
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index,1).toString();
        String stuff = model.getValueAt(index, 2).toString();
        String quantity = model.getValueAt(index, 3).toString();
        String cost = model.getValueAt(index, 4).toString();
        String price = model.getValueAt(index, 5).toString();
        String des = model.getValueAt(index, 6).toString();
        this.jTextEditId.setText(id);
        this.jTextEditName.setText(name);
        this.jcmbBoxEditStuff.setSelectedItem(stuff);
        this.jSpinEditQuantity.setValue(Integer.parseInt(quantity));
        this.jcmbBoxEditCost.setSelectedItem(cost);
        this.jTextEditPrice.setText(price);
        this.jTextAreaEditDes.setText(des);
    }
    private void handleEditSave(){
        try{
            int row = this.jtblEditProduct.getSelectedRow();
            String id;
            String name;
            String stuff;
            String quantity;
            String cost;
            String price;
            String des;
            id = this.jtblEditProduct.getValueAt(row, 0).toString();
            if(!id.equals("product id")){
                name = this.jTextEditName.getText();
                stuff = this.jcmbBoxEditStuff.getSelectedItem().toString();
                quantity = this.jSpinEditQuantity.getValue().toString();
                cost = this.jcmbBoxEditCost.getSelectedItem().toString();
                price = this.jTextEditPrice.getText();
                des = this.jTextAreaEditDes.getText();
                DefaultTableModel model = (DefaultTableModel) this.jtblNewProduct.getModel();
                model.addRow(new Object [] {id, name, stuff, quantity, cost, price, des});
                DefaultTableModel model_temp = (DefaultTableModel) this.jtblEditProduct.getModel();
                model_temp.setValueAt(id, row, 0);
                model_temp.setValueAt(name, row, 1);
                model_temp.setValueAt(stuff, row, 2);
                model_temp.setValueAt(quantity, row, 3);
                model_temp.setValueAt(cost, row, 4);
                model_temp.setValueAt(price, row, 5);
                model_temp.setValueAt(des, row, 6);
            }
        }catch(Exception e){
            this.jlblEditWrong.setText("<html>PLEASE CHOOSE THE PRODUCT<br/> BY CLICK TO ROW ON TABLE LEFT SIZE.</html>");
        }
    }
    private void handleEditRemove(){
        try{
        int index = this.jtblEditProduct.getSelectedRow();
        String id = this.jtblEditProduct.getValueAt(index, 0).toString();
        DefaultTableModel model_edit = (DefaultTableModel) this.jtblEditProduct.getModel();
        model_edit.removeRow(index);
        DefaultTableModel model_temp = (DefaultTableModel) this.jtblTemplate.getModel();
        DefaultTableModel model_new = (DefaultTableModel) this.jtblNewProduct.getModel();
        for(int i = this.jtblTemplate.getRowCount() - 1; i >= 0; i--){
            if(id.equals(this.jtblTemplate.getValueAt(i, 0).toString()))
                model_temp.removeRow(i);
        }
        for(int i = this.jtblNewProduct.getRowCount() - 1; i >= 0; i--){
            if(id.equals(model_new.getValueAt(i, 0).toString()))
                model_new.removeRow(i);
        }
        }catch(Exception e){
            this.jlblEditWrong.setText("NOT THING TO REMOVE");
        }
    }
    private void handleNewPriceAdd(){
        String price = this.jTextNewPrice.getText();
        String temp = this.jprd_control.setPrePrice(price);
        if(this.jprd_control.checkProductPrice(price) == false){
            this.jlblNewPrice.setText("<html>Price only<br/> focus number</html>");
            
        }else{
            this.jlblNewPrice.setText("");
        }
        this.jTextNewPrice.setText(temp);
    }
    private void handleViewOverview(){
        clearViewOverview();
        String attr_s = this.jcmbBoxViewall.getSelectedItem().toString();
        String id, name;
        String [] rows;
        int Rows = this.jtblTemplate.getRowCount();
        DefaultTableModel model = (DefaultTableModel) this.jtblViewProducts.getModel();
        DefaultTableModel model_temp = (DefaultTableModel) this.jtblTemplate.getModel();
        if(attr_s.equals("Default")){
            for(int i = 0; i < Rows; i++){
                rows = new String [2];
                id = model_temp.getValueAt(i, 0).toString();
                name = model_temp.getValueAt(i, 1).toString();
                rows[0] = id;
                rows[1] = name;
                model.addRow(rows);
            }
        }
    }
    private void clearViewOverview(){
        DefaultTableModel model = (DefaultTableModel)this.jtblViewProducts.getModel();
        int rows = model.getRowCount();
        while(rows > 0){
            model.removeRow(rows - 1);
            rows--;
        }
    }
    private void handleViewViewDetail(){
        DefaultTableModel model = (DefaultTableModel)this.jtblViewDetails.getModel();
        DefaultTableModel model_pre = (DefaultTableModel)this.jtblViewProducts.getModel();
        String [] rows = new String [7];
        if(model.getRowCount()>0)
            model.removeRow(0);
        int index = this.jtblViewProducts.getSelectedRow();
        String id, name, stuff, quantity, cost, price, des;
        id = model_pre.getValueAt(index, 0).toString();
        name = model_pre.getValueAt(index, 1).toString();
        stuff = "";
        quantity = "";
        cost = "";
        price = "";
        des = "";
        DefaultTableModel model_temp = (DefaultTableModel)this.jtblTemplate.getModel();
        int len = model_temp.getRowCount() - 1;
        while(len >= 0){
            if(model_temp.getValueAt(len, 0).equals(id)){
                stuff = model_temp.getValueAt(len, 2).toString();
                quantity = model_temp.getValueAt(len, 3).toString();
                cost = model_temp.getValueAt(len, 4).toString();
                price = model_temp.getValueAt(len, 5).toString();
                des = model_temp.getValueAt(len, 6).toString();
                break;
            }         
            len--;
        }
        rows[0] = id;
        rows[1] = name;
        rows[2] = stuff;
        rows[3] = quantity;
        rows[4] = cost;
        rows[5] = price;
        rows[6] = des;
        model.addRow(rows);
    }
}
